### ISSUE TITLE
Prevent PR being merge when it is in WIP status

### ISSUE THREAD

**Issue by jbinda** [IvanFon/super-labeler-action#11]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Currently I'm using [github wip app](https://github.com/apps/wip) to make check task in "ongoing" state.

I wonder if we can provide some similar feature to `super-labeler` ( in e.g fail one of the task if the WIP status is applied)

**Comment by IvanFon** [comment]
My only concern with this is that it would increase the scope of this action. Something similar that I thought of could be automatically requesting reviews based on labels, but these things start to extend it beyond just a labeler.

Do you have an example of what a JSON config would look like for this feature? That's another concern - it may make configs more complicated.

As an alternative, you could combine this with another action such as https://github.com/yogevbd/enforce-label-action, which will block merging based on which labels are applied.

As for this specific use case (WIP PRs), Github has a draft feature which already prevents merging (although there are some problems - you can't turn an existing, non-draft PR into a draft PR, and some people have complained about it being too hard to distinguish drafts in the PR list).

**Comment by jbinda** [comment]
>As an alternative, you could combine this with another action such as https://github.com/yogevbd/enforce-label-action, which will block merging based on which labels are applied.

Yes I thought about something when you set label in e.g. `DO_NOT_MERGE` then the merging wont be able.

This one is nice to have I think because there is other action that you can pick. However still it's nice to have in one place :)

**Comment by IvanFon** [comment]
I’ve thought about it, and I’m going to mark this wontfix for now, for two reasons:

- At this point, I think it’s outside of the scope of this action. I’d love to target more general workflows, but right now I’m going to focus on making the best labeler possible.
- [Github already has a draft feature that does this out of the box](https://github.blog/2019-02-14-introducing-draft-pull-requests/) - ideally the `isDraft` condition would be for applying labels other than a WIP status.
- One of the main features of Github Actions is being able to easily use several different actions together, so I think combining this labeler with other actions is a good recommendation.

I have created a `revisit` label (might rename it later), to remember to revisit these features if the scope of the project changes.

Again, thank you for the suggestion!
