### ISSUE TITLE
isOpen condition type

### ISSUE THREAD

**Issue by jbinda** [IvanFon/super-labeler-action#15]
**Describe the bug**
I have noticed that the label is not applied when you expect 2 conditions in which one of them is `isOpen` type. Check config in config section below. It appear in pr labeling as well. 

I'm pretty sure it is connected with case sensitive match in `isOpen.ts` file.

Check PR #16  which should fix that.

**Expected behavior**

**Config**
```json
  "issue": {
    "bug": {
      "requires": 2,
      "conditions": [
        {
          "type": "titleMatches",
          "pattern": "/^bug/i"
        },
        {
          "type": "isOpen",
          "value": true
        }
      ]
    }
}
```

**Comment by IvanFon** [comment]
Fixed in #16
