### ISSUE TITLE
How to label `filesMatch`

### ISSUE THREAD

**Issue by jbinda** [IvanFon/super-labeler-action#2]
As I mentioned in my PR comment I was trying to migrate feature to match path of afected files to put proper label on PR.

Unfortunately the labels that I expected is not applied. Other mathers like `branchMatch` of `titleMatch` works fine. I wonder if I'm doing something wrong. 

According to readme I pass below configuration to put `Web` label if some file from folder `packages/web/src/**/*` is affected, see JSON snippet

```json
    "web": {
      "requires": 1,
      "conditions": [
        {
          "type": "filesMatch",
          "glob": "packages/web/src/**/*"
        }
      ]
    }
```

@IvanFon  Do you have any idea what can be wrong here ?

**Comment by IvanFon** [comment]
Sorry, I haven't tested `filesMatch` very much yet, so there may still be some bugs.

I didn't release `filesMatch` to `v1` yet, are you using `IvanFon/super-labeler-action@master`?

**Comment by jbinda** [comment]
>I didn't release filesMatch to v1 yet, are you using IvanFon/super-labeler-action@master?

yep, that was the reason :) Thanks

**edited:**
According to above we can close this issue (anyway it was more a question that a bug)
